// AUTO-GENERATED by scripts/fetch-publications.mjs
// Source: OpenAlex API (https://openalex.org)
// To refresh: npm run fetch-publications
import type { Publication } from "./publications";
export const publications: Publication[] = [
  {
    "title": "Exploring Citizens’ Perceptions of Urban Well-Being Through a Card-Based Game",
    "year": 2026,
    "venue": "article",
    "doi": "https://doi.org/10.1145/3772318.3791611",
    "citedBy": 1,
    "openAccessUrl": "https://doi.org/10.1145/3772318.3791611",
    "type": "article"
  },
  {
    "title": "Engaging People with Intellectual Disabilities in IoT Prototyping: Design Guidelines for Accessible Making Toolkits",
    "year": 2026,
    "venue": "SpringerBriefs in applied sciences and technology",
    "doi": "https://doi.org/10.1007/978-3-032-12359-6_2",
    "citedBy": 0,
    "openAccessUrl": "https://link.springer.com/content/pdf/10.1007/978-3-032-12359-6_2.pdf",
    "type": "book-chapter"
  },
  {
    "title": "Mapping sidewalk accessibility with smartphone imagery and Visual AI: a participatory approach",
    "year": 2024,
    "venue": "Philosophical Transactions of the Royal Society A Mathematical Physical and Engineering Sciences",
    "doi": "https://doi.org/10.1098/rsta.2024.0106",
    "citedBy": 5,
    "openAccessUrl": null,
    "type": "article"
  },
  {
    "title": "A rapid-prototyping toolkit for people with intellectual disabilities",
    "year": 2024,
    "venue": "International Journal of Human-Computer Studies",
    "doi": "https://doi.org/10.1016/j.ijhcs.2024.103347",
    "citedBy": 6,
    "openAccessUrl": "https://www.sciencedirect.com/science/article/pii/S1071581924001307",
    "type": "article"
  },
  {
    "title": "MakeNodes: Opening connected-IoT making to people with intellectual disability",
    "year": 2024,
    "venue": "International Journal of Human-Computer Studies",
    "doi": "https://doi.org/10.1016/j.ijhcs.2024.103325",
    "citedBy": 1,
    "openAccessUrl": "http://dx.doi.org/10.1016/j.ijhcs.2024.103325",
    "type": "article"
  },
  {
    "title": "\"This Sounds Unclear\": Evaluating ChatGPT capability in translating end-user prompts into ready-to-deploy Python Code.",
    "year": 2024,
    "venue": "article",
    "doi": "https://doi.org/10.1145/3656650.3656693",
    "citedBy": 1,
    "openAccessUrl": "https://dl.acm.org/doi/pdf/10.1145/3656650.3656693",
    "type": "article"
  },
  {
    "title": "A Rapid-Prototyping Toolkit for People with Intellectual Disabilities",
    "year": 2024,
    "venue": "SSRN Electronic Journal",
    "doi": "https://doi.org/10.2139/ssrn.4768775",
    "citedBy": 0,
    "openAccessUrl": "https://doi.org/10.2139/ssrn.4768775",
    "type": "preprint"
  },
  {
    "title": "Improving Swim Accessibility through Vibro-Tactile Sensory Substitution: A Preliminary Study",
    "year": 2023,
    "venue": "article",
    "doi": "https://doi.org/10.1145/3605390.3605418",
    "citedBy": 4,
    "openAccessUrl": "https://dl.acm.org/doi/pdf/10.1145/3605390.3605418",
    "type": "article"
  },
  {
    "title": "Designing integrated physical–digital systems for children–nature interaction",
    "year": 2023,
    "venue": "International Journal of Child-Computer Interaction",
    "doi": "https://doi.org/10.1016/j.ijcci.2023.100582",
    "citedBy": 9,
    "openAccessUrl": "https://www.sciencedirect.com/science/article/pii/S2212868923000193",
    "type": "article"
  },
  {
    "title": "Design for social digital well-being with young generations: Engage them and make them reflect",
    "year": 2023,
    "venue": "International Journal of Human-Computer Studies",
    "doi": "https://doi.org/10.1016/j.ijhcs.2023.103006",
    "citedBy": 40,
    "openAccessUrl": "https://www.sciencedirect.com/science/article/pii/S1071581923000125",
    "type": "article"
  },
  {
    "title": "Ready, Steady, Go: Playing and Rapidly Designing with IoTgo",
    "year": 2022,
    "venue": "article",
    "doi": "https://doi.org/10.1145/3531073.3534463",
    "citedBy": 0,
    "openAccessUrl": "https://bia.unibz.it/esploro/outputs/abstract/Ready-Steady-Go-Playing-and-Rapidly/991006786292301241",
    "type": "article"
  },
  {
    "title": "A Phygital Toolkit for Rapidly Designing Smart Things at School",
    "year": 2022,
    "venue": "article",
    "doi": "https://doi.org/10.1145/3531073.3531119",
    "citedBy": 10,
    "openAccessUrl": "https://bia.unibz.it/esploro/outputs/conferenceProceeding/A-Phygital-Toolkit-for-Rapidly-Designing/991006785790901241",
    "type": "article"
  },
  {
    "title": "Designing Integrated Product-Service Systems for Children-Nature Interaction",
    "year": 2022,
    "venue": "SSRN Electronic Journal",
    "doi": "https://doi.org/10.2139/ssrn.4180094",
    "citedBy": 0,
    "openAccessUrl": "https://doi.org/10.2139/ssrn.4180094",
    "type": "article"
  },
  {
    "title": "COBO: A Card-Based Toolkit for Co-Designing Smart Outdoor Experiences with People with Intellectual Disability",
    "year": 2021,
    "venue": "Lecture notes in computer science",
    "doi": "https://doi.org/10.1007/978-3-030-85623-6_11",
    "citedBy": 5,
    "openAccessUrl": "https://inria.hal.science/hal-04330961",
    "type": "book-chapter"
  },
  {
    "title": "A Card-based Toolkit for Co-Designing Smart Interactive Experiences with Subjects with Neurodevelopmental Disorders.",
    "year": 2020,
    "venue": "article",
    "doi": null,
    "citedBy": 0,
    "openAccessUrl": null,
    "type": "article"
  }
];

export const publicationsFetchedAt = "2026-05-20T17:13:43.010Z";
